### PR TITLE
PractitionerRole

### PR DESCRIPTION
**Pull request by saulakravitz**
This is my initial attempt to flesh out PractitionerRole, Healthcareservice, and Endpoint.
Builds without efforts on dev6 branch.  There may be issues with uscore alignment, naming conventions, etc.

### CODE REVIEW

**Comment by mlterryMitre** [comment]
@saulakravitz - will ultimately defer to @markkramerus to weigh in but at this time, rather than make changes directly to shr.core, it would be preferable if you just opened a JIRA ticket and have the core SHR modeling team address it.  You can even be prescriptive in the details of the JIRA ticket of what exact lines to change.  That would allow us to better understand your perspective.

**Comment by cmoesel** [comment]
@saulakravitz had asked about support for PractitionerRole, and after learning that it was not supported, set out to develop it himself since he needed it.  I encouraged him to submit a PR as we didn't want the work to get lost.  As an open source project, I assumed that PRs were our preferred mode of operation...  If we don't want PRs on SHR spec, we should better define what the expectations are.

**Comment by cmoesel** [comment]
@markkramerus -- @saulakravitz does not have permission to branch off our repo.  That's why he's on a fork.  If we will accept contributions outside our team, they will always come in on forks.

If you click the "command line instructions" link at the bottom of the PR, it shows you how you can get Saul's changes locally.  You only want to follow what's in Step 1 (Step 2 is how you actually merge it into `dev6` if/when you approve).

image

**Comment by cmoesel** [comment]
@markkramerus -- I told @saulakravitz to build off `dev6` because `master` is 150+ commits _behind_ `dev6` and currently does not compile under SHR CLI 6.4.0 because it violates so many of the Element/Entry/Group rules.  With so much that's changed in `dev6` I didn't think it made sense for him to be authoring off the 2-month old `master`.

**Comment by mlterryMitre** [comment]
@markkramerus - can we take a step back and formalize a process for contributing changes before doing this? 
Our SHR model is in flight and some contributors not involved in day-to-day SHR discussions are not always aware of what is planned in our development branches to be knowing what will break or not.
In the meantime, @saulakravitz - can you enter in a JIRA ticket on this?  Makes sense to at least track what the issue is rather than bury it in a commit/pull request.

**Comment by saulakravitz** [comment]
@mlterryMitre : where to leave the jira breadcrumb?
This is about fleshing out the resources supporting the davinci plan-net as both a pedagogical exercise and an insurance policy in case the ONC plan-net developers fail/bail.

**Comment by mlterryMitre** [comment]
@saulakravitz - duly noted on its importance.  It's just helpful to track what is being changed in SHR first as a feature enhancement in https://standardhealthrecord.atlassian.net/secure/RapidBoard.jspa?projectKey=SHRM&rapidView=6&view=planning.
This will allow some transparency among the SHR team members and also track history of feature enhancements that can be tied to shr_spec commits and pull requests.

**Comment by saulakravitz** [comment]
https://standardhealthrecord.atlassian.net/browse/SHRM-7

**Comment by markkramerus** [comment]
Saul, see pull request #369 .  I'm closing this in favor of that PR.

**Pull request closed without merging**
